spring.datasource.url=jdbc:postgresql://db.pwseympdatacxcpnqsfq.supabase.co:5432/postgres?sslmode=require&preferQueryMode=simple&options=-4
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.default_schema=escuela_db
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8086
